// импорт библиотек для работы с файлом csv

In [256]:
import pandas as pd
import numpy as np

// Запись в переменную файла и его чтение.

In [257]:
df = pd.read_csv('vgsales_12.csv')
df

Rank                                  Name Platform    Year       Genre   
0    15197           Let's Play Flight Attendant       DS  2010.0  Simulation  \
1     5292                           Mini Ninjas       DS  2009.0      Action   
2     3119                     SingStar Pop Hits      PS2  2007.0        Misc   
3    13923                        Super Army War      GBA  2005.0      Action   
4     7564       Rocket Power: Zero Gravity Zone      GBA  2003.0      Sports   
..     ...                                   ...      ...     ...         ...   
548   6409                    Ultimate NES Remix      3DS  2014.0      Action   
549  11069           Jambo! Safari Animal Rescue      Wii  2009.0  Simulation   
550   2311  Tiger Woods PGA Tour 12: The Masters      PS3  2011.0      Sports   
551   8992                        Elf: The Movie      GBA  2004.0      Action   
552   8048            Fear Effect 2: Retro Helix       PS  2001.0      Action   

                       Publisher  NA_Sales  EU_Sales  JP_Sales  Other_Sales   
0                    Deep Silver      0.02      0.00       0.0         0.00  \
1              Eidos Interactive      0.17      0.15       0.0         0.04   
2    Sony Computer Entertainment      0.00      0.50       0.0         0.15   
3               Flashpoint Games      0.03      0.01       0.0         0.00   
4                            THQ      0.14      0.05       0.0         0.00   
..                           ...       ...       ...       ...          ...   
548                      Unknown      0.15      0.09       0.0         0.02   
549                         Sega      0.07      0.01       0.0         0.01   
550              Electronic Arts      0.52      0.26       0.0         0.12   
551          Crave Entertainment      0.10      0.04       0.0         0.00   
552            Eidos Interactive      0.10      0.07       0.0         0.01   

     Global_Sales  
0            0.02  
1            0.35  
2            0.65  
3            0.04  
4            0.20  
..            ...  
548          0.27  
549          0.09  
550          0.90  
551          0.15  
552          0.18  

[553 rows x 11 columns]

// Кол-во строк и столбцов

In [258]:
df.shape

(553, 11)

// Заголовки столбцов в файле csv

In [259]:
df.head()

Rank                             Name Platform    Year       Genre   
0  15197      Let's Play Flight Attendant       DS  2010.0  Simulation  \
1   5292                      Mini Ninjas       DS  2009.0      Action   
2   3119                SingStar Pop Hits      PS2  2007.0        Misc   
3  13923                   Super Army War      GBA  2005.0      Action   
4   7564  Rocket Power: Zero Gravity Zone      GBA  2003.0      Sports   

                     Publisher  NA_Sales  EU_Sales  JP_Sales  Other_Sales   
0                  Deep Silver      0.02      0.00       0.0         0.00  \
1            Eidos Interactive      0.17      0.15       0.0         0.04   
2  Sony Computer Entertainment      0.00      0.50       0.0         0.15   
3             Flashpoint Games      0.03      0.01       0.0         0.00   
4                          THQ      0.14      0.05       0.0         0.00   

   Global_Sales  
0          0.02  
1          0.35  
2          0.65  
3          0.04  
4          0.20

// Описание столбцов

In [260]:
df.describe()

Rank         Year    NA_Sales    EU_Sales    JP_Sales   
count    553.000000   545.000000  553.000000  553.000000  553.000000  \
mean    8601.157324  2006.603670    0.293544    0.171573    0.074919   
std     4967.619803     5.754217    0.947373    0.518348    0.409051   
min       16.000000  1981.000000    0.000000    0.000000    0.000000   
25%     4288.000000  2003.000000    0.000000    0.000000    0.000000   
50%     8947.000000  2008.000000    0.070000    0.020000    0.000000   
75%    13037.000000  2011.000000    0.220000    0.120000    0.030000   
max    16579.000000  2016.000000   14.970000    5.360000    6.040000   

       Other_Sales  Global_Sales  
count   553.000000    553.000000  
mean      0.052604      0.592604  
std       0.158886      1.768225  
min       0.000000      0.010000  
25%       0.000000      0.050000  
50%       0.010000      0.150000  
75%       0.030000      0.460000  
max       1.670000     21.820000

// Поиск занчения по Rank = 7564

In [261]:
df.where(df['Rank'] == 7564).dropna()

Rank                             Name Platform    Year   Genre Publisher   
4  7564.0  Rocket Power: Zero Gravity Zone      GBA  2003.0  Sports       THQ  \

   NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales  
4      0.14      0.05       0.0          0.0           0.2

// Краткая сводка об столбцах в csv

In [262]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 553 entries, 0 to 552
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Rank          553 non-null    int64  
 1   Name          553 non-null    object 
 2   Platform      553 non-null    object 
 3   Year          545 non-null    float64
 4   Genre         553 non-null    object 
 5   Publisher     553 non-null    object 
 6   NA_Sales      553 non-null    float64
 7   EU_Sales      553 non-null    float64
 8   JP_Sales      553 non-null    float64
 9   Other_Sales   553 non-null    float64
 10  Global_Sales  553 non-null    float64
dtypes: float64(6), int64(1), object(4)
memory usage: 47.6+ KB


// Удаление строки по индексу

In [263]:
df.drop(axis=0, index=0)

Rank                                  Name Platform    Year       Genre   
1     5292                           Mini Ninjas       DS  2009.0      Action  \
2     3119                     SingStar Pop Hits      PS2  2007.0        Misc   
3    13923                        Super Army War      GBA  2005.0      Action   
4     7564       Rocket Power: Zero Gravity Zone      GBA  2003.0      Sports   
5     6249         Dead Rising 2: Off the Record     X360  2011.0      Action   
..     ...                                   ...      ...     ...         ...   
548   6409                    Ultimate NES Remix      3DS  2014.0      Action   
549  11069           Jambo! Safari Animal Rescue      Wii  2009.0  Simulation   
550   2311  Tiger Woods PGA Tour 12: The Masters      PS3  2011.0      Sports   
551   8992                        Elf: The Movie      GBA  2004.0      Action   
552   8048            Fear Effect 2: Retro Helix       PS  2001.0      Action   

                       Publisher  NA_Sales  EU_Sales  JP_Sales  Other_Sales   
1              Eidos Interactive      0.17      0.15       0.0         0.04  \
2    Sony Computer Entertainment      0.00      0.50       0.0         0.15   
3               Flashpoint Games      0.03      0.01       0.0         0.00   
4                            THQ      0.14      0.05       0.0         0.00   
5                         Capcom      0.17      0.09       0.0         0.02   
..                           ...       ...       ...       ...          ...   
548                      Unknown      0.15      0.09       0.0         0.02   
549                         Sega      0.07      0.01       0.0         0.01   
550              Electronic Arts      0.52      0.26       0.0         0.12   
551          Crave Entertainment      0.10      0.04       0.0         0.00   
552            Eidos Interactive      0.10      0.07       0.0         0.01   

     Global_Sales  
1            0.35  
2            0.65  
3            0.04  
4            0.20  
5            0.28  
..            ...  
548          0.27  
549          0.09  
550          0.90  
551          0.15  
552          0.18  

[552 rows x 11 columns]

// Замена значения to_replace на value

In [264]:
df.replace(to_replace='Mini Ninjas', value="Big Ninjas")

Rank                                  Name Platform    Year       Genre   
0    15197           Let's Play Flight Attendant       DS  2010.0  Simulation  \
1     5292                            Big Ninjas       DS  2009.0      Action   
2     3119                     SingStar Pop Hits      PS2  2007.0        Misc   
3    13923                        Super Army War      GBA  2005.0      Action   
4     7564       Rocket Power: Zero Gravity Zone      GBA  2003.0      Sports   
..     ...                                   ...      ...     ...         ...   
548   6409                    Ultimate NES Remix      3DS  2014.0      Action   
549  11069           Jambo! Safari Animal Rescue      Wii  2009.0  Simulation   
550   2311  Tiger Woods PGA Tour 12: The Masters      PS3  2011.0      Sports   
551   8992                        Elf: The Movie      GBA  2004.0      Action   
552   8048            Fear Effect 2: Retro Helix       PS  2001.0      Action   

                       Publisher  NA_Sales  EU_Sales  JP_Sales  Other_Sales   
0                    Deep Silver      0.02      0.00       0.0         0.00  \
1              Eidos Interactive      0.17      0.15       0.0         0.04   
2    Sony Computer Entertainment      0.00      0.50       0.0         0.15   
3               Flashpoint Games      0.03      0.01       0.0         0.00   
4                            THQ      0.14      0.05       0.0         0.00   
..                           ...       ...       ...       ...          ...   
548                      Unknown      0.15      0.09       0.0         0.02   
549                         Sega      0.07      0.01       0.0         0.01   
550              Electronic Arts      0.52      0.26       0.0         0.12   
551          Crave Entertainment      0.10      0.04       0.0         0.00   
552            Eidos Interactive      0.10      0.07       0.0         0.01   

     Global_Sales  
0            0.02  
1            0.35  
2            0.65  
3            0.04  
4            0.20  
..            ...  
548          0.27  
549          0.09  
550          0.90  
551          0.15  
552          0.18  

[553 rows x 11 columns]

Создаём таблицу данных с поомщью DataFrame

In [265]:
p6 = pd.DataFrame(
    [[1,1,1,1],
     [1,1,1,1],
     [1,1,1,1]],
     columns=['id','name','age','data'])
p6

id  name  age  data
0   1     1    1     1
1   1     1    1     1
2   1     1    1     1

Заменяем все значения data 1 на 12.04.2023

In [266]:
p6 = p6.replace({'data' : 1}, '12.06.2023')
p6

id  name  age        data
0   1     1    1  12.06.2023
1   1     1    1  12.06.2023
2   1     1    1  12.06.2023

// Импорт класса SimpleImputer

In [267]:
from sklearn.impute import SimpleImputer

// Работа с классом SimpleImputer

In [268]:
imputer = SimpleImputer(missing_values = np.nan, strategy ='mean')
data = [[99, np.nan, 2], [45, 12, np.nan], [np.nan, 10, 20]]
 
print("Оригинальный набор чисел : \n", data)
imputer = imputer.fit(data)
 
data = imputer.transform(data)
 
print("Измененный набор чисел : \n", data)

Оригинальный набор чисел : 
 [[99, nan, 2], [45, 12, nan], [nan, 10, 20]]
Измененный набор чисел : 
 [[99. 11.  2.]
 [45. 12. 11.]
 [72. 10. 20.]]


// Отображения уникальный значений столбца Platform и его кол-ва 

In [269]:
print('Количество уникальных платформ', len(df.Platform.unique()))
print("Наименования платформы", df.Platform.unique())

Количество уникальных платформ 23
Наименования платформы ['DS' 'PS2' 'GBA' 'X360' 'PC' 'PS' '3DS' 'XB' 'GC' 'XOne' 'WiiU' 'Wii'
 'PS3' 'PSV' 'PSP' 'PS4' 'SAT' 'SNES' 'N64' 'GB' 'NES' 'DC' '2600']


In [270]:
df.to_csv('vgsales_12.csv', index=False)
df

Rank                                  Name Platform    Year       Genre   
0    15197           Let's Play Flight Attendant       DS  2010.0  Simulation  \
1     5292                           Mini Ninjas       DS  2009.0      Action   
2     3119                     SingStar Pop Hits      PS2  2007.0        Misc   
3    13923                        Super Army War      GBA  2005.0      Action   
4     7564       Rocket Power: Zero Gravity Zone      GBA  2003.0      Sports   
..     ...                                   ...      ...     ...         ...   
548   6409                    Ultimate NES Remix      3DS  2014.0      Action   
549  11069           Jambo! Safari Animal Rescue      Wii  2009.0  Simulation   
550   2311  Tiger Woods PGA Tour 12: The Masters      PS3  2011.0      Sports   
551   8992                        Elf: The Movie      GBA  2004.0      Action   
552   8048            Fear Effect 2: Retro Helix       PS  2001.0      Action   

                       Publisher  NA_Sales  EU_Sales  JP_Sales  Other_Sales   
0                    Deep Silver      0.02      0.00       0.0         0.00  \
1              Eidos Interactive      0.17      0.15       0.0         0.04   
2    Sony Computer Entertainment      0.00      0.50       0.0         0.15   
3               Flashpoint Games      0.03      0.01       0.0         0.00   
4                            THQ      0.14      0.05       0.0         0.00   
..                           ...       ...       ...       ...          ...   
548                      Unknown      0.15      0.09       0.0         0.02   
549                         Sega      0.07      0.01       0.0         0.01   
550              Electronic Arts      0.52      0.26       0.0         0.12   
551          Crave Entertainment      0.10      0.04       0.0         0.00   
552            Eidos Interactive      0.10      0.07       0.0         0.01   

     Global_Sales  
0            0.02  
1            0.35  
2            0.65  
3            0.04  
4            0.20  
..            ...  
548          0.27  
549          0.09  
550          0.90  
551          0.15  
552          0.18  

[553 rows x 11 columns]

In [271]:
p6.to_csv('p6.csv', index=False)